# Generated by Django 5.2 on 2025-07-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={"verbose_name": "Doctor", "verbose_name_plural": "Doctors"},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name": "Patient", "verbose_name_plural": "Patients"},
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="special",
            new_name="specialization",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="mobile",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
