# Generated by Django 5.2 on 2025-07-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0004_alter_doctor_address_alter_doctor_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="address",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
